# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  # - repo: https://github.com/ansible-community/ansible-lint
  #   rev: v6.4.0
  #   hooks:
  #     - id: ansible-lint

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.9.0
    hooks:
      - id: python-no-eval
      - id: python-check-mock-methods

  - repo: https://github.com/google/yapf
    rev: main # This should be moved to a tag after the next release post v0.32.0, I am guessing v0.33
    hooks:
      - id: yapf
