---

galaxy_info:
  author: dtasev
  description: Configures and runs a nginx instance to serve the staticfiles of the autoreduce-frontend
  license: MIT
  min_ansible_version: 2.1
  platforms:
    - name: CentOS7

dependencies: []
