---

- name: Pull the docker container to get any updates
  become: yes
  community.docker.docker_image:
    name: ghcr.io/autoreduction/autoreduce:latest
    source: pull

- name: Start the container
  community.docker.docker_container:
    name: webapp
    image: ghcr.io/autoreduction/autoreduce-frontend:latest
    state: started
    env:
      AUTOREDUCTION_PRODUCTION: "true"
    volumes:
      - /home/{{ autoreduction_user }}/.autoreduce:/home/{{ autoreduction_user }}/.autoreduce:rw
      - /instrument:/instrument:rw
      - /isis:/isis
      - /isis:/archive
      - /shared-config:/shared-config
      - /staticfiles:/staticfiles:rw
    detach: yes
    comparisons:
      image: strict
    published_ports:
      - 8000:8000
