name: Tests
on: [ push ]

jobs:
  selenium:
    name: Selenium
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ISISScientificComputing/autoreduce-actions@master
        with:
          package_name: autoreduce_frontend

      - name: Set up chromedriver
        run: |
          wget https://chromedriver.storage.googleapis.com/87.0.4280.20/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          export PATH=$PATH:./chromedriver_linux64/

      - name: Install chrome
        run: sudo apt-get install -y google-chrome-stable

      - name: Run tests
        run: |
          pytest autoreduce_frontend --cov-report=xml --cov=autoreduce_frontend

      - uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          name: codecov-umbrella
          flags: webapp
          fail_ci_if_error: true
          verbose: true

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: screenshots_and_reports
          path: |
            ~/.autoreduce/selenium_tests/screenshots
            ~/.autoreduce/selenium_tests/a11y_reports


  dependency-check:
    name: Dependency-Check
    runs-on: ubuntu-18.04
    container: ubuntu/bionic
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ job.container.image }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ job.container.image }}-pip-

      - name: Pip install
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .


  Inspection:
    name: Code Inspection
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - uses: ISISScientificComputing/autoreduce-actions@master
        with:
          package_name: autoreduce_frontend

      - name: Pylint tests
        run: |
          PYTHONPATH=autoreduce_frontend pylint --load-plugins pylint_django autoreduce_frontend

      - name: YAPF
        run: python -m yapf --parallel --diff --recursive .

      - name: Vulture
        run: vulture --min-confidence 90 autoreduce_frontend

